app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    # ファイルの一覧ページ
    path('', views.FileListView.as_view(), name='file_list'),

    # 通常のフォーム
    path('single/upload/', views.SingleUploadView.as_view(), name='single_upload'),

    # モデルフォーム
    path('single/upload/model/', views.SingleUploadWithModelView.as_view(), name='single_upload_with_model'),

    # 複数ファイルを通常フォーム
    path('multi/upload/', views.MultiUploadView.as_view(), name='multi_upload'),

    # 複数ファイル、モデルフォーム
    path('multi/upload/model/', views.multi_upload_with_model, name='multi_upload_with_model'),

    # input multiple
    path('input/multiple/upload/', views.InputMultiUploadView.as_view(), name='input_multi'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models


class UploadFile(models.Model):
    """アップロードされたファイルを表すモデル"""
    file = models.ImageField('画像ファイル')

    def __str__(self):
        """ファイルのURLを返す"""
        return self.file.url

app/forms.py
from django import forms
from django.core.files.storage import default_storage
from .models import UploadFile


class SingleUploadForm(forms.Form):
    file = forms.ImageField(label='画像ファイル')

    def save(self):
        upload_file = self.cleaned_data['file']
        file_name = default_storage.save(upload_file.name, upload_file)
        return default_storage.url(file_name)


class SingleUploadModelForm(forms.ModelForm):

    class Meta:
        model = UploadFile
        fields = '__all__'


class BaseUploadFormSet(forms.BaseFormSet):

    def save(self):
        # ['/media/1.png', '/media/2.png']のようなファイルのURLが入ったリストになる
        url_list = []

        # SingleUploadFormのsaveを順に呼び出し、ファイルURLを集める
        for form in self.forms:
            try:
                url = form.save()
            except KeyError:
                # ファイルがアップロードされていないフォームは、KeyErrorになるので、ここで無視する
                pass
            else:
                url_list.append(url)
        return url_list


UploadFormSet = forms.formset_factory(SingleUploadForm, formset=BaseUploadFormSet, extra=5)

UploadModelFormSet = forms.modelformset_factory(
    UploadFile, form=SingleUploadModelForm,
    extra=3
)


class MultipleUploadForm(forms.Form):
    file = forms.ImageField(
        label='画像ファイル',
        widget=forms.ClearableFileInput(attrs={'multiple': True})
    )

    def save(self):
        url_list = []
        for upload_file in self.files.getlist('file'):
            file_name = default_storage.save(upload_file.name, upload_file)
            file_path = default_storage.url(file_name)
            url_list.append(file_path)
        return url_list

app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from .forms import SingleUploadForm, SingleUploadModelForm, UploadFormSet, UploadModelFormSet, MultipleUploadForm
from .models import UploadFile


class SingleUploadView(generic.FormView):
    form_class = SingleUploadForm
    template_name = 'app/upload.html'

    def form_valid(self, form):
        download_url = form.save()
        context = {
            'download_url': download_url,
            'form': form,
        }
        return self.render_to_response(context)


class SingleUploadWithModelView(generic.CreateView):
    """ファイルモデルのアップロードビュー"""
    model = UploadFile
    form_class = SingleUploadModelForm
    template_name = 'app/upload.html'
    success_url = reverse_lazy('app:file_list')


class FileListView(generic.ListView):
    """アップロードされたファイルの一覧ページ"""
    model = UploadFile


class MultiUploadView(generic.FormView):
    form_class = UploadFormSet
    template_name = 'app/upload.html'

    def form_valid(self, form):
        download_url_list = form.save()
        context = {
            'download_url_list': download_url_list,
            'form': form,
        }
        return self.render_to_response(context)


def multi_upload_with_model(request):
    formset = UploadModelFormSet(request.POST or None, files=request.FILES or None, queryset=UploadFile.objects.none())
    if request.method == 'POST' and formset.is_valid():
        formset.save()
        return redirect('app:file_list')

    context = {
        'form': formset
    }

    return render(request, 'app/upload.html', context)


class InputMultiUploadView(generic.FormView):
    form_class = MultipleUploadForm
    template_name = 'app/upload.html'

    def form_valid(self, form):
        download_url_list = form.save()
        context = {
            'download_url_list': download_url_list,
            'form': form,
        }
        return self.render_to_response(context)

app/templates/app/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>ファイルアップロード</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

app/templates/app/upload.html
{% extends 'app/base.html' %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">送信</button>
    </form>

    {% if download_url %}
        <a href="{{ download_url }}">{{ download_url }}</a>
    {% endif %}

    {% for download_url in download_url_list %}
        <p><a href="{{ download_url }}">{{ download_url }}</a></p>
    {% endfor %}
{% endblock %}

app/templates/app/uploadfile_list.html
{% extends 'app/base.html' %}

{% block content %}
    <p><a href="{% url 'app:single_upload_with_model' %}">ファイルアップロードへ</a></p>
    <p><a href="{% url 'app:single_upload' %}">ファイルアップロード(モデルなし)へ</a></p>
    <p><a href="{% url 'app:multi_upload_with_model' %}">ファイル一括アップロードへ</a></p>
    <p><a href="{% url 'app:multi_upload' %}">ファイル一括アップロード(モデルなし)へ</a></p>
    <p><a href="{% url 'app:input_multi' %}">ファイル一括アップロード(input multiple モデルなし)へ</a></p>

    <h1>ファイルの一覧</h1>
    {% for uploadfile in uploadfile_list %}
        <p><a href="{{ uploadfile.file.url }}">{{ uploadfile.file.url }}</a></p>
    {% endfor %}
{% endblock %}